language: node_js
deploy:
  provider: npm
  email: bitard.michael@gmail.com
  api_key:
    secure: AnT88ZlRzar6WwOfm1HueDDoBcPgh0pFLwsrYS1fK7v6pcdthg+ZJwg585cfGOwRXAZdBLH+hrV8jD17OljDrigOt8gHceeYVAMDGDuOqeOKRObAz023aW+wNW2+dYslFFbdCNYNGB5wmjRVEsI/pjRtJfe4loXpq6gbWgMStjlGc0EwNth05OiEi9rIN9zMczU7JAR3IXxrcoqJ18EPCCp6oIW4BHMUy+ZvRtcQW0EPEaqp1cZXV8NbOVQi0ikHX5zr3HIEMI1ZuXFkzzDKg19UcynW00XqvAkTsXQERioCA7vSqL8CZvIfotxDxSpUOXLJZAU5bG/YLSn7rbjIuYFntulXUx8YMNsWN46hd058+QXCTdZPtI4uddo01pKQlmIyktxrhJsFnfbyherbGDdJ4dckqwoPU7l+fTgRcVvy8KEVdP5wmtPRy85Fwjmo91gXEvosKn/FXqTEw1FPcmtgCU+Fz1aEAMQkQvZ3JvzJZjxfnRKWJu82qMNK+X0qlkVjDePlqHPB7fXj5TqjhOoAtFXVDAgDjx3jmpAV4QLfHoRPutmzBM+Ut8SpROBxD0mopOvl9m5q84Ox3qojoq7jqtJzBQ0mBk6+hYhpoSFeF13/XicqYJ4G1ttMNff13uLCv+0VoYLmUxqN3Mhhe0CmbhOLwDxW3Q8OiX2xCbo=
  on:
    tags: true
    repo: agileek/hubot-signal
